name: VanillaHead
version: '1.0.0'
main: com.example.vanillahead.VanillaHead  # <-- проверь, что пакет совпадает с твоим Java-классом
api-version: '1.20'
authors: [servernablydate1]
description: Plugin for VanillaHead
